name: Build and Release Universal Tool

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install PyInstaller and create the .exe with the new name
      - name: Build executable
        run: |
          pip install pyinstaller
          pyinstaller --onefile main.py  # Replace with your main script

      # Rename the .exe file to Universal Tool.exe and archive it
      - name: Rename and archive the .exe
        run: |
          mkdir -p release
          mv dist/main.exe "release/Universal Tool.exe"

      # Upload the renamed .exe file to GitHub Releases
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: "release/Universal Tool.exe"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
