name: Build and Release .exe

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.13'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install PyInstaller and create the .exe
      - name: Build executable
        run: |
          pip install pyinstaller
          pyinstaller --onefile --icon=misc\tool_icon.ico --uac-admin main.py  # Replace with your main script

      # Archive the .exe file for GitHub release
      - name: Archive the .exe
        run: |
          mkdir release
          copy dist\main.exe release\main.exe
          echo "Creating archive complete"

      # Upload to GitHub Releases
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/main.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Get the tag comments and latest tag
      - name: Get tag details
        id: get_tag_details
        run: |
          TAG_NAME=$(git describe --tags --abbrev=0)
          COMMENTS=$(git tag -l --format='%(contents)' "$TAG_NAME")
          echo "tag_name=$TAG_NAME" >> $GITHUB_ENV
          echo "comments=$COMMENTS" >> $GITHUB_ENV

      # Send a request to Slack workflow
      - name: Notify Slack
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"body\": \"${{ env.comments }}\", \"version\": \"${{ env.tag_name }}\"}" \
          ${{ secrets.SLACK_WEBHOOK_URL }}
