name: Notify Slack

on:
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  notify:
    runs-on: windows-latest
    
    steps:
      # Get the tag details
      - name: Get tag details
        id: get_tag_details
        shell: pwsh
        run: |
          $TAG_NAME = git describe --tags --abbrev=0
          $COMMENTS = git tag -l --format='%(contents)' $TAG_NAME
          echo "tag_name=$TAG_NAME" >> $env:GITHUB_ENV
          echo "comments=$COMMENTS" >> $env:GITHUB_ENV

      # Send a request to Slack
      - name: Notify Slack
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"text\": \"A new release has been published!\\nTag: ${{ env.tag_name }}\\nComments: ${{ env.comments }}\"}" \
          ${{ secrets.SLACK_WEBHOOK_URL }}
