name: Test Get Tag and Notify Slack

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  test:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Get the tag details
      - name: Get tag details
        id: get_tag_details
        shell: pwsh
        run: |
          # Get the latest tag
          $TAG_NAME = git describe --tags --abbrev=0
          
          # Extract the tag message
          $TAG_MESSAGE = git tag -l --format="%(contents)" $TAG_NAME
          
          # Output the tag name and message as environment variables
          echo "tag_name=$TAG_NAME" >> $env:GITHUB_ENV
          echo "tag_message=$TAG_MESSAGE" >> $env:GITHUB_ENV

      # Notify Slack
      - name: Notify Slack
        shell: pwsh
        run: |
          # Prepare the payload
          $body = @{
              body = $env:tag_message
              version = $env:tag_name
          } | ConvertTo-Json -Depth 2

          # Send the notification
          Invoke-RestMethod -Uri ${{ secrets.SLACK_WEBHOOK_URL }} -Method Post -ContentType 'application/json' -Body $body
